### PR TITLE
Add feature to assign coupons to vendor.

### LINKED ISSUE #861: Creating Coupons for specific Vendors as Admin
**Is your feature request related to a problem? Please describe.**
Currently, admins cannot assign coupons to vendors.  Admins must be able to assign coupons to vendors

**Additional context**

https://wordpress.org/support/topic/how-to-make-a-coupon/
https://www.wcvendors.com/help/topic/creating-coupons-as-admin-for-specific-vendors/

### PR DESCRIPTION
**Pull request by mahlamusa**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add a new feature to assign coupons to vendors. Admin can choose a vendor in a single coupon edit screen or use bulk edit to assign a vendor to multiple orders at once.

Closes wcvendors/wcvendors-pro#1692 

### How to test the changes in this Pull Request:

Single coupon edit screen.
1. Add or create a coupon as an administrator
2. Check that there is a 'Vendor' meta box with a vendor select field
3. Search, select vendor, and publish or update coupon.
4. Check the assigned vendor was saved and preselected after saving.

Bulk coupon edit screen.
1. Go to the Coupons page, and select multiple coupons by checking the corresponding checkboxes or the select all checkbox.
2. Select 'Edit' in bulk actions and click 'Apply'
3. Check that there is a 'Vendor' dropdown
4. Search, select vendor, and click update to perform the bulk update.
5. Check that all the selected coupons have been assigned to the selected vendor.

Check the UI is consistent for the Product and Coupon edit screen
1. Check single coupon screen shows the same Vendor meta box as the single coupon screen
2. Use bulk edit coupons and bulk edit products to check the Vendor select box looks and works the same

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by Mrlunsuper — CHANGES_REQUESTED** [review]
There are 2 vendors select box when enabled Pro
image

**Comment by Mrlunsuper** [comment]
Duplicate vendors store name in the coupon table 
image

**Review by Mrlunsuper — CHANGES_REQUESTED** [review]
Duplicate vendors store names in the coupon table 
image

**Review by Mrlunsuper — APPROVED** [review]

**Comment by digitalchild** [comment]
Can we update "Author to vendor" on the various screens?

Coupons_‹_WC_Vendors_—_WordPress
 
Why was the UI changed for assigning a vendor to a coupon between the coupon screens and product screens? 

Edit_coupon_“xyz03”_‹_WC_Vendors_—_WordPress

**Comment by mahlamusa** [comment]
> Can we update "Author to vendor" on the various screens?
> 
> Why was the UI changed for assigning a vendor to a coupon between the coupon screens and product screens?
> 

All updated. I have changed the UI to be consistent across the screens.

**Review by Mrlunsuper — APPROVED** [review]

**Review by ketulsheth85 — APPROVED** [review]

**Comment by mahlamusa** [comment]
Addressed by https://github.com/wcvendors/wcvendors-pro/pull/1695

**Pull request closed without merging**
