### PR TITLE
Update is_vendor_product()

### PR DESCRIPTION
**Pull request by dvrcthewrld**
Update is_vendor_product() to check vendor role against custom set vendor name

### CODE REVIEW

**Comment by digitalchild** [comment]
The vendor role internally is never changed from vendor only the label changes. This method will always return 'Vendor' no matter what you set the display names to be. Is this doing something that I am missing?

**Comment by dvrcthewrld** [comment]
Has that always been the case?

I help out with ConsciousCrafties.com, and their Vendor role is actually "Craftie".  The reason I recommended this change was because I discovered this problem when diagnosing the failure of the Vacation message to appear.

**Comment by dvrcthewrld** [comment]
I think that they (CC) may have changed the name of their vendor role years ago.  The result is that the Role **name** is "Craftie", but the role slug remains **vendor**.

The `wcv_get_user_role()` function is used, it seems, in just one place between both WCV and WCV Pro.  It returns the role name, rather than the role slug, which I think would be preferable.  (In the past, before you implemented the option for a custom name, I would say that the name was best, but no longer.)  When it gets used, it is used in `is_vendor_product_page()`, which itself places it within `is_vendor_product()`.  And `is_vendor_product()` checks that the role is equal to precisely (`===`) "Vendor".

Might I suggest that instead of the commit already proposed here, the following two changes be made:

 `is_vendor_product()` could do a case-insensitive string comparison `strcasecmp()`
AND
`wcv_get_user_role()` could return the role slug rather than its name?

Such changes would be entirely safe with the existing codebase and would resolve the issue that is created by administrators who once renamed their vendor role to something other than "Vendor".

**Comment by dinhtungdu** [comment]
I think we should use strict comparison in `is_vendor_product` for role slug because it will never change. And `wcv_get_user_role` should return role slug as you suggest :).

**Comment by dvrcthewrld** [comment]
New PR #560 introduced instead of this one, per @dinhtungdu suggestions.

**Comment by dinhtungdu** [comment]
Thank @dvrcthewrld, I will review your PR as soon as I can :)

**Comment by digitalchild** [comment]
Closing in favour of #560

**Pull request closed without merging**
