### PR TITLE
Fixed: Vendor select box empty for marketplaces which has over 100 vendors #614

### LINKED ISSUE #614: Vendor select box empty for marketplaces which has over 100 vendors
**Describe the bug**
> By limiting the number of results at 100 in $user_args = array( [...] 'number' => 100 );, the $selected option is now useless, because it will show blank for products where the respective vendor id is not found among those first 100 (in the case of 3000 vendors, the products belonging to 2900 of them will have a blank option selected).
> If the vendor of a product is not among those 100, the product meta box will show empty, like this -> http://prntscr.com/qj7om1.

Originally reported by @RobertMpop  https://github.com/wcvendors/wcvendors/commit/39c9b473e7cbeefc212b23415513568579967d48#commitcomment-36652039

### PR DESCRIPTION
**Pull request by dinhtungdu**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:
Add current vendor to vendor dropdown list to prevent empty select box for marketplaces that have over 100 vendors.

Closes #614.

### CODE REVIEW

**Comment by dinhtungdu** [comment]
@RobertMPop Can you please review this PR to confirm if the issue is fixed?

**Comment by RobertMPop** [comment]
@dinhtungdu, the `'include'` solution is a nice one (dang, I should've thought of it :) ) and it works well on the product's edit page. 

However, it doesn't work on the quick edit screen and I really can't figure it out why.

**Comment by dinhtungdu** [comment]
Hmm, quick edit is working on my end. What is the current behavior? Can you give me some gifs or screenshots?

**Comment by digitalchild** [comment]
Product edit page vendor drop-down still isn't searching. The search vendor drop-down does work on the quick edit page.

**Pull request merged**
