### PR TITLE
Fixed: Sold by label spacing on single product page

### LINKED ISSUE #597: "Sold By" label's colon spacing is not same for the archive pages and order page
**Describe the bug**
There is no space for some of the pages like the archive page(product category page).
and for the Order page, where the colon is double like so: https://cl.ly/1d37b95f4aa5

**To Reproduce**
1. Go to an archive page, a category page for example
2. check the Sold by label:
3. You can see the difference from the shop page as the Sold by label should be something like so: "Sold by: Vendor name"

In the Orders page:
1.) Go to Orders tab and see the "By::" label

**Screenshots**
"Sold by Label" - https://cl.ly/050043bd7cef
"By::" label : https://cl.ly/1d37b95f4aa5

**Expected behavior**
"Sold By:" label should have space like the ones in the product single page - https://cl.ly/fb8e332719ad
"By::" label should only have one colon symbol ":"

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by digitalchild**
### All Submissions:

* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #597

### How to test the changes in this Pull Request:

1. Sold by label on single product page always had a space after label and separator
2. Check the sold by spacing on all aspects of the site are now universal with no space

### CODE REVIEW

**Comment by digitalchild** [comment]
It's not supposed to have a space. I removed it from the one place there was a space. There should be no spaces between Sold by: and the colon.

**Comment by dinhtungdu** [comment]
@digitalchild but there is no space between vendor store and 'Sold by:', for example: `Sold By:Vendor2 Store`

**Comment by digitalchild** [comment]
@dinhtungdu where is this?

**Comment by dinhtungdu** [comment]
@digitalchild the listing page: https://prnt.sc/q3q7p3
Just testing: @dinhtungdu

**Comment by digitalchild** [comment]
@dinhtungdu before we had inconsistent output, some had space some didn't. For consistency and clearer to read I decided on spaces on either side for all. If that isn't the case, then people can now change it via the filter.

**Pull request merged**
