### PR TITLE
Enable Paypal AP chained mode

### PR DESCRIPTION
**Pull request by infiniteschema**
It appears there have been kludge solutions to this floating around for a while but I'd say it's time for a proper one, no?

On sole vendor checkouts this will set the vendor to the "primary" receiver, making them responsible for chargebacks/fees/etc, and the customer payment will go directly to them. The site is the "secondary" receiver, and will receive its commission forwarded from the vendor.

On any non-sole vendor checkouts, it will revert to parallel payment.

Enable chained payments via the following simple code in functions.php:

```
/* Enable Paypal AP chained mode
 * @requires Sole vendor per checkout
 */
function my_wcv_is_chained() {
    return true;
}
add_filter('wcv_is_chained', 'my_wcv_is_chained');
```

Enable sole vendor checkouts via the following simple code in functions.php:

```
/* Sole vendor per checkout
 */
function my_woocommerce_add_to_cart_validation($valid, $product_id, $quantity) {
    $author_added = WCV_Vendors::get_vendor_from_product( $product_id );
    foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
        $author = WCV_Vendors::get_vendor_from_product( $cart_item['product_id'] );
        if ($author != $author_added) {
            wc_add_notice( __('Your cart can only contain products from one seller at a time - '
                    . 'please checkout or clear your cart before adding this item.'), 'error' );
            return false;
        }
    }

    return true;
}
add_filter('woocommerce_add_to_cart_validation', 'my_woocommerce_add_to_cart_validation', 999, 3);
```

:moneybag: :moneybag: :moneybag:

### CODE REVIEW

**Comment by digitalchild** [comment]
Although this solution might work in specific instances it requires too many variables in place to be useful. The problem you have is that to become the primary receiver you need to have a chained payments approved account. That means ALL vendors would need to add their API details to the marketplace which would be an absolute mess and almost impossible to have work seamlessly. Here is the quote from the paypal website: 

> Important: If you allow a third party to PayPal to execute an application on your behalf, the third party becomes the API caller because the party is now calling the Adaptive Payments API. The third party must also have permission from PayPal to use the advanced service. For example, if an application supports chained payments, both you and the third party must have permission to use the service.

The only option to support chained payments with this solution is for the marketplace to be the primary receiver.

**Comment by infiniteschema** [comment]
@digitalchild, I have tested this solution and fortunately it does not work in the manner you've suggested. It only requires the application's API details, the same as parallel. In fact, if you carefully read the quoted text you provided in the context you're suggesting, it would apply equally to chained payments with the application as the primary receiver, as it makes no distinction between primary/secondary. So, that quoted text appears to be referring to a different use case which is not applicable here. It would be nonsensical for Paypal to require all vendors to sign up for and provide their API credentials just to use chained payments considering the very reason for the Adaptive Payments API is to allow these sorts of marketplace transactions to occur seamlessly (not that Paypal has never been nonsensical before, of course, but that doesn't seem to be the case here).

Please feel free to test this solution and I think you will see that it works as stated.

**Comment by bentasm1** [comment]
PayPal does not approve chained payments for WC Vendors customers.  They approve parallel payments and mass pay.  Despite them all being parts of the adaptive payments API, it may work for some, but not for others, and we can not risk breaking 15,000 customers websites. :(  (as fun as that might be though! :))

**Comment by digitalchild** [comment]
I spoke to the paypal adaptive payments team about this and the bit I quote is directly from the chained payments section only. Chained payments is made for apps and API calls for single instances and for the marketplace to be the primary receiver not vendors. It might work with the marketplace credentials but I wouldn't be surprised if paypal bans both the accounts for misuse. 

https://developer.paypal.com/docs/classic/adaptive-payments/integration-guide/APIntro/ 

If you scroll down to Adaptive Payments Service Permissions you will see that chained payments requires specific permission from paypal to use. Which would in fact mean you'd need all vendors to have chained payments accounts. I know this also as I had a customer for a solution I built years ago that wanted this and it just wasn't possible.

**Comment by infiniteschema** [comment]
Hmm. Couldn't _any_ code change potentially break 15,000 customers' websites? I thought that was the point of testing? This pull request is only a few lines added and a few lines changed - it should be pretty quick & easy to review/test and see that it wouldn't affect any sites which did not explicitly enable it via their functions.php.

If PayPal does not approve chained payments for WC Vendors customers, then why was the [Paypal Adaptive Payments - Chained](https://gist.github.com/digitalchild/00565df0939e7fde14eb) gist created by @digitalchild previously? I found numerous threads on wcvendors.com where customers were advised directly from PayPal to make the vendor the primary receiver and the site secondary, for exactly the reasons I've stated (chargeback responsibility, etc). Besides, if it's just a matter of getting API approval from PayPal for chained payments, then that's just part of the process, just like it is getting API approval from PayPal for parallel payments... Right?

Anyhow, there seems to be a lot of pushback on this, despite the fact that numerous customers seem to have been clamoring for this functionality for years and having to use a kludge to enable it. So, if there is some other business reason you don't want this implemented (you think less people will purchase the Stripe plugin or something like that) then just let me know and I'll happily drop it. I'm only here to contribute and improve this plugin, after all - I don't have anything to gain. But if it's just a case of misunderstanding then I will continue to try to clarify to your liking as necessary. Again, just a simple review/test of the code/process to confirm this works should be pretty quick and straightforward.

**Comment by digitalchild** [comment]
That code I provided was actually originally provided by matt gates and barely tested. The reason it was only a gist is because we cannot support it with chained payments being such a huge mess to implement from application to build.  Anyone that wanted to use this code needed to have the market place as the primary receiver. The people at paypal that recommended the vendor as the primary receiver were not the API team from paypal but level 1 support people and were wrong.

**Comment by infiniteschema** [comment]
@digitalchild well, okay. I found a number of places in the forums where PayPal explicitly directed the site owner to make the vendor the primary receiver, and themselves secondary... and my testing confirms that it works as expected. So if you spoke to them, I'd wager they misunderstood the case. But, if you don't think it should be implemented, I'll drop it.

**Comment by infiniteschema** [comment]
@digitalchild okay.

**Comment by digitalchild** [comment]
I'll email paypal again and try and get 100% confirmation as I have been working with their API dev team for a while now. If not, we can always just spin up a new plugin with this code in it.

**Comment by infiniteschema** [comment]
@digitalchild okay. An alternative solution I came up with which would actually be even more flexible would be to add a hook to modify the $payRequest object just before the  `$response = $service->Pay( $payRequest );` call. Then it'd be easy to do this via a plugin, etc.

**Comment by infiniteschema** [comment]
That ^ may be much easier if there was also a hook to modify the `$receivers` array just after the `$receivers    = $this->get_receivers( $order );` call. I'm not sure, haven't explored how to modify the receivers once they are part of the `$payRequest` object.

**Comment by digitalchild** [comment]
This is going in the too hard basket, until someone can make this work without breaking 99% of our marketplaces.

**Comment by infiniteschema** [comment]
To be clear - again - my submitted solution would break 0 marketplaces, as it maintains the existing functionality by default and only enables the alternate mode if explicitly enabled by the site owner. It was also confirmed to work precisely as stated (in both the existing and alternate modes) via testing. However, even with no negative impact this solution was met with resistance from the start for some reason, despite many examples of users having repeatedly requested this functionality, so I'll happily drop it. If wcvendors ever has an opportunity to actually test the code and confirm that it works properly as stated and does not break anything, please feel free to merge it in, or convert it to a plugin if need be.

**Comment by digitalchild** [comment]
Hello, apologies, I didn't read through the code well enough. Teach me for reading pull requests in the middle of the night. I'll re-open and then when I get some time to test in chained mode, if its all good i'll add it. The other concern I have is that anyone that did enable chained payments had so many issues with paypal configurations and site configuration that it turns into a support nightmare. I think with some decent documentation we can alleviate a lot of that.

**Comment by digitalchild** [comment]
Hello, any chance you can update your PR to fix the conflict?

**Comment by digitalchild** [comment]
Adaptive payments is depreciated closing

**Pull request closed without merging**
