### PR TITLE
Allow orders to be unmarked shipped

### PR DESCRIPTION
**Pull request by crabilld**
On the front dashboard, clicking "Unmark shipped" will work with this code. This code is based on [this answer from SO](http://stackoverflow.com/a/7225113/944054).

### CODE REVIEW

**Comment by crabilld** [comment]
It's an improvement, but I have noticed that the system isn't complete. For instance, whenever something is unmarked shipped, it will be added as a "Marked as shipped" comment on the orders page. Also, it's not possible to unmark something as shipped in the backend.

To do this the "right" way would really require something more than a toggle. For instance, if you click "Mark shipped" and then keep refreshing the resulting page, it's shipment status will flipflop with "Marked as shipped" comments accumulating. The url parameter for marking and unmarking an order as shipped really need to be unique.

**Comment by bentasm1** [comment]
The biggest reason we disabled the "Unship" is because novice/newbie vendors would click shipped, then unclick shipped, then click shipped, or click shipped for orders that didnt even need shipping.  Then the customer gets an email and says "Hey, wtf is with this?".  Perhaps an upgrade could be made to those considerations that brought them to be disabled to begin with.  Food for thought.

**Comment by MattyLB** [comment]
Can a confirmation modal be added with a warning like "An email will
be sent to your customer. Please confirm or cancel."

Same modal would be a great place to ask for the tracking # and carrier
if the shipment tracking plugin is installed.

:)

**Comment by crabilld** [comment]
That makes sense. I personally just want the functionality for vendors to manage orders, not for customers to be notified. This is also true of commenting: I was surprised when the comments went to customers, so I disabled it. I like the shipped (aka order complete) and commenting features without notifications attached.

**Comment by digitalchild** [comment]
This will not be integrated but if you create an issue for this we can add this to the features request. As mentioned it would require a bit more work than a simple toggle.

**Comment by crabilld** [comment]
I agree, it just leaves too many problems still open. I've gone ahead and completely disabled/hidden the mark shipped functionality on my site. I think, at the very least, the text shouldn't toggle to "unmark shipped", which is confusing for the user.

**Pull request closed without merging**
