### PR TITLE
Fixed: Order status not getting updated while initiating a part refun…

### LINKED ISSUE #827: Order status not getting updated while initiating a part refund.
**Describe the bug**
Customer places an order including products from different vendors. Then after when the admin initiates a refund for a single product from the order, the status is not updated for the admin. 

**Steps to reproduce:**
1. Place an order for multiple products in a single order. (Customer)
2. Admin initiates a refund for a single product.
3. Check the status in the commission's table.

Note: The status is updated for both the admin and the vendor when a full refund is initiated.

**Screenshots**
Screenshot_15
Screenshot_16

**Expected behavior**
The status must be changed from 'Due' to 'Reversed' for both the admin and the vendor.

### PR DESCRIPTION
**Pull request by Mrlunsuper**
…d. #827

### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #827 .

### How to test the changes in this Pull Request:

1. Run an order
2. Run manually refund for that order item
3. Check commissions table and see both admin and vendor commission status was reversed

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

**Review by bdesai1982 — CHANGES_REQUESTED** [review]
@Mrlunsuper A single order consisting of multiple variable products is placed by a customer and when the admin manually initiates a refund for the entire order, the status in the commission table does not get updated to 'Reversed'.
Screenshot_2
Screenshot_3
.

**Review by bdesai1982 — CHANGES_REQUESTED** [review]
Customer places an order and admin edits the order, then admin changes the status to refunded and updates the order. check the commission table, vendor status is not updated.
Screenshot_3

**Comment by bdesai1982** [comment]
@Mrlunsuper Customer places an order for multiple products from the same vendor. Then the vendor requests a refund for a single product from the admin. When the admin approves the refund request for a single product, the status of the other products also gets updated to"Partial-refund".
Screenshot_7

**Comment by Mrlunsuper** [comment]
Fixed by https://github.com/wcvendors/wc-vendors-gateway-stripe-connect-v2/pull/124

**Review by digitalchild — APPROVED** [review]

**Review by digitalchild — APPROVED** [review]

**Review by bdesai1982 — CHANGES_REQUESTED** [review]
@Mrlunsuper The status of the order does get updated while initiating a part refund, but the status of all the variable products in the order gets updated instead of the products for which the refund was initiated.

**Review by bdesai1982 — APPROVED** [review]

**Pull request merged**
