### PR TITLE
Fix emails not working properly

### PR DESCRIPTION
**Pull request by mahlamusa**
https://github.com/wcvendors/wcvendors/issues/423

### CODE REVIEW

**Comment by digitalchild** [comment]
Can you please fix these merge conflicts?

**Comment by mahlamusa** [comment]
Conflict fixed.

**Comment by digitalchild** [comment]
Emails still aren't triggering for applications to the vendors or to the admin

**Comment by digitalchild** [comment]
https://github.com/wcvendors/wcvendors/pull/425/commits/fc2f99b001eedcc467b02da051d509f93090ac8b is the old way to include the emails. From 2.0.0 I changed to the same mechanism that WooCommerce uses in its email classes. 

Can you explain why you changed it to this?

**Comment by mahlamusa** [comment]
I changed this because it is considered bad coding practice to use included files as function calls. Also part of the file includes the files first and then instantiate the classes, so for consistency on the same file I had to change it to use the same way of including the files.

**Pull request merged**
